name = "docsbot-screenshot"
main = "src/index.ts"
compatibility_date = "2023-03-14"
node_compat = true
workers_dev = true


browser = { binding = "mybrowser" }
r2_buckets  = [
  { binding = "puppeteer", bucket_name = "docsbot"}
]

[vars]
bucketUrl = "https://cdn.docsbot.com"